version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - ./pgdata:/docker-entrypoint-initdb.d
  web:
    image: beus3256/go-test-service
    restart: always

    ports:
      - "8000:8000"


